<?php
/**
 * FilmTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Association de cinéphile
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FilmTest Class Doc Comment
 *
 * @category    Class */
// * @description Film
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FilmTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Film"
     */
    public function testFilm()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "titre"
     */
    public function testPropertyTitre()
    {
    }

    /**
     * Test attribute "duree"
     */
    public function testPropertyDuree()
    {
    }

    /**
     * Test attribute "synopsys"
     */
    public function testPropertySynopsys()
    {
    }

    /**
     * Test attribute "date_sortie"
     */
    public function testPropertyDateSortie()
    {
    }

    /**
     * Test attribute "les_realisateurs"
     */
    public function testPropertyLesRealisateurs()
    {
    }

    /**
     * Test attribute "les_acteurs"
     */
    public function testPropertyLesActeurs()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }
}
